---
title: "water col nuts release"
author: "Dunia"
date: "7/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library(dplyr)
library(plyr)
library(tidyr)
library(docstring)
```
Read files
```{r}
PP <- read.csv("../Read Only/PP erosion fluxes.csv")[, -1]
nut <-  c("NH4", "NO2", "NO3", "PO4", "DSi")
```

```{r}

```



```{r}
flux_spd <- function(data = NutEro[NutEro$Speed != 0, ], sits, nut,  data_acc = PP[, c(1:3, 18:20)]) {
  #'@title Nutrients released per speed
  #'@description This function plots the release of different nutrients at different time steps and at different speeds. Suspended particulate matter is not included in this function because the scale is different. It returns a graph of the triplicate.
fluxes <- sites <- location <- reps <- spee <-  nuts <- height <-  rsq <-  NULL
for (s in sits) {
   ss <- data[data$Site == s, ]
   acc <- data_acc[data_acc$Site == s, ]
   locat  <- unique(ss$Location)

   for (i in locat) {
    acc_loc <- subset(acc, acc$Location == i)
    loc <- subset(ss, Location == i)
    repli    <- unique(loc$Replicate)

for (ir in 1:length(repli)) {
      r <- repli[ir]
      acc_r <- acc_loc[ir, ]
      rep <- subset(loc, Replicate == r)
      sped <- unique(rep$Speed)

  for (n in 1:length(nut)) {
    nutname <- nut[n]
     fn <- NULL

     for (p in 1:length(sped)) {
      sp <- sped[p]
      spd <- subset(rep, Speed == sp)
      flux <- lm(spd[,nutname] ~ spd$Timed)
      prob <- summary(flux)$coefficients[2,"Pr(>|t|)"]
      Nutflux <- coef(flux)[2]*(acc_r$HeightWat/100)
      rsqs  <- summary(flux)$adj.r.squared
      prob <- summary(flux)$coefficients[2,"Pr(>|t|)"]
      Nutflux <- coef(flux)[2]*(acc_r$HeightWat/100)
      fn <- c(fn, Nutflux)
      fluxes <- c(fluxes, Nutflux)
      sites <- c(sites, s)
      location <- c(location, i)
      reps <- c(reps, ir)
      spee <- c(spee, sp)
      nuts <- c(nuts, nutname)
      height <- c(height, acc_r$HeightWat/100)
      rsq <- c(rsq, rsqs)
    }}}}}
   invisible(data.frame(Site = sites, Location = location, Nut = nuts, Rep = reps, Speed = spee, Fluxes = fluxes, Height = height, rsq = rsq))
}
```

```{r}
FluxSPM <- function(data = NutEro[NutEro$Speed != 0 & !is.na(NutEro$Turbidity.gl),], sits, data_acc = PP[,c(1:3,18:20)]) {
  #'@Title Suspended matter released per speed
  #'@Description this function plots the concentration of suspended matter released at different speeds and time steps
fluxes <- sites <- location <- reps <- spee <-  nuts <- height <-  rsq <-  NULL

for (s in sits){
   ss       <- data[data$Site == s, ]
   acc <- data_acc[data_acc$Site == s, ]
   locat  <- unique(ss$location)

   for (i in locat){
    acc_loc <- subset(acc, acc$Location == i)
    loc <- subset(SS, Location == i)
    repli    <- unique(Loc$Replicate)

for (ir in 1:length(repli)){
      r <- repli[ir]
      acc_r <- acc_loc[ir, ]
      rep <- subset(loc, Replicate == r)
      sped <- unique(Rep$Speed)

     fn <- NULL

     for (p in 1:length(Sped)) {
       sp <- Sped[p]
       spd <- subset(rep, Speed == sp)

      flux <- lm(spd$Turbidity.gl ~ spd$Timed)
      prob <- summary(flux)$coefficients[2,"Pr(>|t|)"]
      nutflux <- coef(flux)[2]*(acc_r$HeightWat/100)

      rsqs  <- summary(flux)$adj.r.squared
      prob <- summary(flux)$coefficients[2,"Pr(>|t|)"]
      nutflux <- coef(flux)[2]*(acc_r$HeightWat/100)
      fn <- c(fn, Nutflux)

    fluxes <- c(fluxes, nutflux)
    sites <- c(sites, s)
    location <- c(location, i)
    reps <- c(reps, ir)
    spee <- c(spee, sp)
     nuts <- c(nuts, "Turbidity.gl")
     height <- c(height, acc_r$HeightWat/100)
     rsq <- c(rsq, rsqs)
    }}}}
   invisible(data.frame(Site = sites, Location = location, Nut = nuts, Rep = reps, Speed = spee, Fluxes = fluxes, Height = height, rsq = rsq))
}

FluxSpeed <- rbind(flux_spd(data = PP[PP$Speed != 0, ],sits = "PP", nut = nut), FluxSPM(data = PP[PP$Speed != 0, ],sits = "PP"))
```
```{r}
write.csv(FluxSpeed, "../Project generated/Fluxes erosion per speed.csv")
fluxper_speed <- read.csv("../Project generated/Fluxes erosion per speed.csv")[, -1] 
fluxper_speed <- aggregate(fluxper_speed[, 6], by = list(Location = fluxper_speed$Location, Nut = fluxper_speed$Nut,Speed = fluxper_speed$Speed), FUN = mean)
fluxper_speed[, 4] <- round(fluxper_speed[, 4], digits = 2)
colnames(fluxper_speed)[4] <- "ExpFlux"
```

```{r fig.height=5, fig.width=15}
#These plots are not including the nutrients of nitrate (NO3) and DSi because they did not show a clear correlation between erosion and changes in the concentration in the water column.
plotreltur <- function(Data, Station, nut = c("NH4", "NO2", "PO4"), col, SPD = fluxper_speed){
  Sites <- Data[Data$Site == Station, ]
  Loc <- unique(Data$Location)
  Rep <- unique(Data$Replicate)
  SPDSit <- SPD[SPD$Site == Station, ]

png(paste0("../Project generated/",Station, "SpeedFlux.png"),width = 900, height = 280)
     
  par(mfrow = c(1,4), mar = c(2, 2, 3, 2), oma = c(4,4,4,2))
  for (n in 1:length(nut)){
    Nutname <- nut[n]
    SPDNut <- SPD[SPD$Nut == Nutname,]
    plot(y = Sites[, Nutname], x = Sites$Sample.num, xaxt= "n", type = "n",
          cex.main = 2, cex.axis = 1.5, xlab = "", main = "", ylab = " ")
    
   for (m in Loc) {
      Loca <- subset(Sites, Location == m)
      SPDLoc <- subset(SPDNut, Location == m)
      
      for (r in Rep){
        Repl <- subset(Loca, Replicate == r)
      with (Repl, lines(y = Repl[,Nutname], x = Sample.num, type = "b", col = col[Loc == m]), cex.axis = 1.5)
      }
          axis(side =1, line = 0, at = c(0,5,8,11), labels = c(0,0.149,0.175,0.203), cex.axis = 1.5)
          if (Nutname == "NH4"){
    title(main = expression('NH'[4]^"+"),  line = 1.5, outer = F, cex.main = 2.1)
    } else if (Nutname == "NO2"){
      title(main = expression('NO'[2]^"-"), outer = F, cex.main = 2.1)
    } else if (Nutname == "PO4"){
      title(main = expression('PO'[4]^"3-"), outer = F, cex.main = 2.1)}
      abline(v = c( 0.5, 3.5, 6.5, 9.5) , col = "black", lty = 2)
      if(m == 25){
      axis(side =3, line = -2.3, at = c(5,8,11), labels = SPDLoc$ExpFlux[SPDLoc$Location == 25], col.axis = col[Loc == m], cex.axis = 1.2, tick = F)} else if(m == 200) {
      axis(side =3, line = -3.3, at = c(5,8,11), labels = SPDLoc$ExpFlux[SPDLoc$Location == 200], col.axis = col[Loc == m], cex.axis = 1.2, tick = F)} 
  }}

  plot(y = Sites[, "Turbidity.gl"], x = Sites$Sample.num, xaxt= "n", type = "n",
           xlab = " ", main = expression('SPM g L'^"-1"), ylab = "g/L", cex.main = 2.1, cex.axis = 1.3, cex.lab = 2)
  SPDNut <- SPD[SPD$Nut == "Turbidity.gl",]
  for (m in Loc) {
      Loca <- subset(Sites, Location == m)
       SPDLoc <- subset(SPDNut, Location == m)
      
      for (r in Rep){
        Repl <- subset(Loca, Replicate == r)
      with (Repl, lines(y = Repl[,"Turbidity.gl"], x = Sample.num, type = "b", col = col[Loc == m]))
      }
     # with (Repl, axis(1, at= Sample.num, labels = Velocity.ms, cex.axis = 1.5))
       axis(side =1, line = 0, at = c(0,5,8,11), labels = c(0,0.149,0.175,0.203), cex.axis = 1.5)
      abline(v = c( 0.5, 3.5, 6.5, 9.5) , col = "black", lty = 2)
       if(m == 25){
      axis(side =3, line = -2.3, at = c(5,8,11), labels = SPDLoc$ExpFlux[SPDLoc$Location == 25], col.axis = col[Loc == m], cex.axis = 1.2, tick = F)} else if(m == 200) {
      axis(side =3, line = -3.3, at = c(5,8,11), labels = SPDLoc$ExpFlux[SPDLoc$Location == 200], col.axis = col[Loc == m], cex.axis = 1.2, tick = F)}
      }
 
  mtext(outer = TRUE, side = 3, line = 1, Sites$Site, cex = 1.8)
  mtext(outer = TRUE, side = 1, line = 2, expression('Velocity m s' ^"-1"), cex = 1.5)
  mtext(outer = TRUE, side = 2, line = 1, expression('mmol m'^"-3"), cex = 1.5)
  
  legend("left", text.col = match(Loc, c("200", "25")), cex = 1.4, bty = "n", legend = Loc ) 
  dev.off()
}
 
color <- c("red", "black")

PP <- PP[order(PP[,6]),]
plotreltur(Data = PP, Station = "PP", col = color)
 
```
